shell = "Ubuntu"


[font]
size = 14

[font.normal]
family = "UbuntuMono Nerd Font"
style = "Regular"

[font.bold]
family = "UbuntuMono Nerd Font"
style = "Bold"

[font.italic]
family = "UbuntuMono Nerd Font"
style = "Italic"

[font.bold_italic]
family = "UbuntuMono Nerd Font"
style = "Bold Italic"

[colors.primary]
background = "#000000"

[window]
opacity = 0.8
blur = true
